FROM jupyter/pyspark-notebook:latest

# Copy your Python script into the image
COPY producer.py /home/jovyan/work/

# Set the working directory
WORKDIR /home/jovyan/work/

# Install additional dependencies if needed
RUN pip install --upgrade pip

RUN pip install pandas SPARQLWrapper requests pika

RUN pip install pyspark

# Set any other configurations or environment variables if needed

# Command to run your Python script
CMD ["sh", "-c", "sleep 7 && python producer.py"]
