# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install the required packages
RUN pip install -r requirements.txt

# Copy the fake user generator script to the working directory
COPY generate_fake_users.py .

# Set the entrypoint to the fake user generator script
CMD ["sh", "-c", "sleep 45 && python generate_fake_users.py"]